version: '3'

services:
  server:
    build: .
    image: server:latest
    ports: 
    - "5000:5000"
    volumes: 
    - .:/src
    environment:
      - FLASK_APP=src/app/server
      - FLASK_ENV='development'
